name: daddy-cycle

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -e .

      - name: Run Daddy
        run: python -m src.the_daddy.cli run
